namespace CKYC.Core.Configuration;

/// <summary>
/// Root configuration object for the CKYC processor. Bound from appsettings.json
/// (or the --settings override) with System.Text.Json.
/// </summary>
public sealed class AppSettings
{
    public DatabaseSettings Database { get; set; } = new();
    public SourceSettings Source { get; set; } = new();
    public CrmSettings Crm { get; set; } = new();
    public BatchSettings Batch { get; set; } = new();
    public FvuSettings Fvu { get; set; } = new();
    public ResponseSettings Response { get; set; } = new();
    public SimulationSettings Simulation { get; set; } = new();
    public RetrySettings Retry { get; set; } = new();
    public SearchSettings Search { get; set; } = new();
    public SearchApiSettings SearchApi { get; set; } = new();
    public UpdateSettings Update { get; set; } = new();
    public DocumentGenerationSettings DocumentGeneration { get; set; } = new();
    public SftpSettings Sftp { get; set; } = new();
}

/// <summary>
/// Per-channel supporting-document generation. During <c>build-zip</c> the generator renders
/// the configured documents for each record's intake channel (e.g. the BCE/<c>beckyc</c>
/// channel gets a filled Aadhaar EKYC report and a client-consent declaration) and attaches
/// channel-neutral documents (e.g. the static undertaking) for every record. Generated bytes
/// are injected straight into the batch's <c>support_docs</c>; nothing is persisted to the
/// document store, so a batch is always produced from current record data.
/// </summary>
public sealed class DocumentGenerationSettings
{
    /// <summary>Master switch. When false, <c>build-zip</c> behaves exactly as before.</summary>
    public bool Enabled { get; set; }

    /// <summary>
    /// Folder holding the document templates. A relative path resolves against the process
    /// working directory; an absolute path is used as-is.
    /// </summary>
    public string TemplateRoot { get; set; } = "doc_format";

    /// <summary>The documents to render. A document with no <see cref="GeneratedDocumentSettings.Channels"/> applies to every channel.</summary>
    public List<GeneratedDocumentSettings> Documents { get; set; } = new();
}

/// <summary>One generated (or statically attached) supporting document.</summary>
public sealed class GeneratedDocumentSettings
{
    /// <summary>Renderer to use: <c>Static</c> (attach the template as-is), <c>Aadhaar</c> or <c>Consent</c>.</summary>
    public string Kind { get; set; } = "Static";

    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Intake-channel values this document applies to (<c>app</c>, <c>beckyc</c>, …). Empty means
    /// every channel — used for the shared undertaking.
    /// </summary>
    public List<string> Channels { get; set; } = new();

    /// <summary>Template file name, relative to <see cref="DocumentGenerationSettings.TemplateRoot"/>.</summary>
    public string Template { get; set; } = string.Empty;

    /// <summary>The record-published file name the generated document replaces (e.g. <c>AdhaarAP.pdf</c>).</summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Record document slots to point at <see cref="FileName"/> (e.g. <c>proofOvd</c>,
    /// <c>currentAddressOvd</c>, <c>clientConsent</c>, <c>declarationDocument</c>).
    /// </summary>
    public List<string> Slots { get; set; } = new();

    // ---- rendering (ignored by the Static renderer) ----
    public string FontFamily { get; set; } = "Arial";
    public float FontSize { get; set; } = 10f;
    public float HeadingFontSize { get; set; } = 12f;
    public string? TextColor { get; set; } = "#101010";

    /// <summary>For the Aadhaar renderer: overlay the record's photo over the template photo.</summary>
    public bool OverlayPhoto { get; set; } = true;

    /// <summary>Coordinate-space width of the template (its native pixel width, or points).</summary>
    public double CoordinateWidth { get; set; }

    /// <summary>Coordinate-space height of the template (its native pixel height, or points).</summary>
    public double CoordinateHeight { get; set; }
}

/// <summary>
/// Per-customer CKYCR search API settings (the pre-batch search that decides whether a
/// customer already exists). "InProcess" uses the deterministic simulator; "Http" points
/// the same client at the real endpoint.
/// </summary>
public sealed class SearchApiSettings
{
    /// <summary>
    /// When false, the pre-batch customer search is skipped entirely: records move straight
    /// from PendingSearch to Searched (using the record-20 search key already present, or a
    /// locally generated one) and no API call is made and no individual_search rows are built.
    /// </summary>
    public bool Enabled { get; set; } = true;

    public string Mode { get; set; } = "InProcess";
    public string BaseUrl { get; set; } = "http://127.0.0.1:5292";
    public string SearchEndpoint { get; set; } = "/api/search";
    public int TimeoutSeconds { get; set; } = 30;
    public int ClaimTimeoutMinutes { get; set; } = 30;

    // Deterministic simulator knob: every Nth customer is treated as "found". 0 disables
    // (all customers simulated as "not found", which exercises the search-key path).
    public int SimulateFoundEvery { get; set; } = 3;

    // ---- failure simulation (retry path) ----
    public bool SimulateErrorsEnabled { get; set; }
    public int SimulateErrorEvery { get; set; }
    public string? SimulateErrorForCustomerId { get; set; }
}

/// <summary>CERSAI upload-response (.UPL.RESm) input settings.</summary>
public sealed class ResponseSettings
{
    // When omitted, response read retains the legacy FVU batch-output location.
    public string? InputRoot { get; set; }
}

/// <summary>CKYCR bulk-update (.UPD) file settings — individual and legal entity updates.</summary>
public sealed class UpdateSettings
{
    public string UserId { get; set; } = "IAU010441";
    public string FiCode { get; set; } = "IN0238";
    public string RegionCode { get; set; } = "01";
    // The update-format sheets show "eg V2.0"; keep the FVU-validated default configurable.
    public string VersionNumber { get; set; } = "V1.1";
    public int SequenceStart { get; set; } = 1;
    public int ClaimTimeoutMinutes { get; set; } = 30;
    public string OutputRoot { get; set; } = "runtime/update";
}

/// <summary>CKYCR individual-search file settings.</summary>
public sealed class SearchSettings
{
    public string UserId { get; set; } = "IRA000337";
    public string FiCode { get; set; } = "IN9797";
    public string RegionCode { get; set; } = "001";
    public string VersionNumber { get; set; } = "V1.1";
    public int SequenceStart { get; set; } = 2;
    public int ClaimTimeoutMinutes { get; set; } = 30;
    public string OutputRoot { get; set; } = "runtime/search";
}

/// <summary>Persistence settings. The "provider" switch lets a SQL Server deployment be used in production.</summary>
public sealed class DatabaseSettings
{
    // SQL Server is the only supported provider after the database migration.
    public string Provider { get; set; } = "sqlserver";
    public string ConnectionString { get; set; } = "Server=(localdb)\\MSSQLLocalDB;Database=CkycCentral;Trusted_Connection=True;TrustServerCertificate=True";
    // Retained for configuration compatibility. DDL is deployment-owned; startup validates it.
    public bool CreateSchemaOnStartup { get; set; }
    public int CommandTimeoutSeconds { get; set; } = 30;
}

/// <summary>Where the daily customer ids come from (step 1).</summary>
public sealed class SourceSettings
{
    // "generate" seeds a deterministic daily set of customer ids for the demo.
    // "file" reads a plain text file with one customer-id per line.
    public string Mode { get; set; } = "generate";
    public string? FilePath { get; set; }
    public int GenerateCount { get; set; } = 12;
    public int GenerateSeed { get; set; } = 20260824;
}

/// <summary>Dummy CRM API wiring. Replace with the production endpoint later.</summary>
public sealed class CrmSettings
{
    // InProcess: an embedded Kestrel server is launched by `crm serve` and used directly.
    // Http: a remote client pointed at an external API (production).
    public string Mode { get; set; } = "InProcess";
    public string BaseUrl { get; set; } = "http://127.0.0.1:5291";
    public string CustomersEndpoint { get; set; } = "/api/customers/{id}";
    public string ListEndpoint { get; set; } = "/api/customers";
    public int TimeoutSeconds { get; set; } = 30;
}

/// <summary>CKYC batch / file naming settings (used when building the .UPL and zip).</summary>
public sealed class BatchSettings
{
    public string UserId { get; set; } = "IAU010441";
    public string FiCode { get; set; } = "IN0238";
    public string RegionCode { get; set; } = "01";
    public string ClientType { get; set; } = "I";
    public string VersionNumber { get; set; } = "V1.1";   // FVU requires V1.1 (ERR_172)
    public int SequenceStart { get; set; } = 1;
    public string OutputRoot { get; set; } = "output";
    public string? AppendedDocSuffix { get; set; }
}

/// <summary>FVU (File Validation Utility) integration + local simulation settings.</summary>
public sealed class FvuSettings
{
    public string ExePath { get; set; } = @"D:\centralprocessing\vendor\FVU_RUN_UTILITY.exe";
    public string WorkspaceRoot { get; set; } = @"D:\centralprocessing\testfvu";
    public string ApiBaseUrl { get; set; } = "http://localhost:9091";
    public string ApiEndpoint { get; set; } = "/api/search-validate/file-with-support";
    public string TriggerSource { get; set; } = "BATCH";
    public int RequestTimeoutSeconds { get; set; } = 600;
    public int StartupTimeoutSeconds { get; set; } = 20;
    public int MaxRetries { get; set; } = 3;
    // true -> run the real FVU_RUN_UTILITY.exe; false -> deterministic local simulation.
    public bool UseRealFvu { get; set; } = true;
}

/// <summary>
/// Deterministic knobs used to demonstrate the "error saving" scenario (step 3) and
/// the FVU failure path, without touching real data.
/// </summary>
public sealed class SimulationSettings
{
    public bool SaveErrorsEnabled { get; set; } = true;

    // Every Nth record save is deliberately failed to exercise the retry path.
    public int SaveErrorEvery { get; set; } = 4;

    // A specific customer id that always fails to save (useful for a targeted test).
    public string? SaveErrorForCustomerId { get; set; }

    // When FVU simulation mode is used with a generated batch, the Nth batch fails validation.
    public int FvuFailEvery { get; set; }

    // ---- CBS fetch retry simulation ----
    // The fetch (step 1) is the retryable example. When enabled, every Nth customer-id's CBS
    // call is made to fail so the retry/backoff path can be exercised. Off by default so the
    // normal end-to-end pipeline is unaffected.
    public bool CbsFetchErrorsEnabled { get; set; }

    // Every Nth customer id fails the CBS fetch (0 disables).
    public int CbsFetchFailEvery { get; set; }

    // A specific customer id that always fails the CBS fetch.
    public string? CbsFetchFailForCustomerId { get; set; }
}

/// <summary>
/// Default retry policy used when seeding the <c>activity_type</c> master. The requested
/// policy is exponential backoff of <see cref="BackoffBaseHours"/> hours (double per failure)
/// with at most <see cref="MaxAttempts"/> tries. Individual activities can override these
/// values in the activity-type master.
/// </summary>
public sealed class RetrySettings
{
    public int MaxAttempts { get; set; } = 3;
    public int BackoffBaseHours { get; set; } = 24;
    public double BackoffMultiplier { get; set; } = 2.0;
}
