namespace CKYC.Core.Domain;

/// <summary>
/// One CERSAI reply detail (record type 100) read from a <c>*.UPL.RESm</c> response file
/// for a single master record. Keeps the full history of everything the CERSAI backend
/// told us about a record — one row per (record, response-file-number). The most recent
/// row's values are also mirrored onto <see cref="MasterRecord"/>'s <c>LastResponse*</c>
/// summary columns so the master row alone tells you the latest known outcome.
/// </summary>
public sealed class MasterRecordResponse
{
    public long Id { get; set; }
    public long MasterRecordId { get; set; }
    public string SourceCustomerId { get; set; } = string.Empty;

    /// <summary>Batch upload file the response belongs to.</summary>
    public string? BatchFile { get; set; }

    /// <summary>The response-file number (the <c>m</c> in <c>*.UPL.RESm</c>).</summary>
    public int ResponseFileNumber { get; set; }

    /// <summary>Full name of the response file this line came from.</summary>
    public string? ResponseFileName { get; set; }

    /// <summary>Running sequence of this detail line within the response file (starts at 1).</summary>
    public int LineNumber { get; set; }

    /// <summary>Line number of the record-20 this refers to in the uploaded batch file.</summary>
    public int? InputRecordLineNumber { get; set; }

    /// <summary>Ack number generated by CERSAI for this record.</summary>
    public string? AckNumber { get; set; }

    /// <summary>Record status code (01 Confirmed Match, 02 No Match, ... ).</summary>
    public string? RecordStatus { get; set; }

    /// <summary>CKYC reference number (record status 01).</summary>
    public string? CkycReferenceNumber { get; set; }

    /// <summary>CKYC number (record status 02).</summary>
    public string? CkycNumber { get; set; }

    /// <summary>Rejection remark, applicable only when the record was rejected.</summary>
    public string? RejectionRemark { get; set; }

    public DateTime? ReadAt { get; set; }
    public string? Remarks { get; set; }

    /// <summary>The raw pipe-delimited response detail line, for audit.</summary>
    public string? RawData { get; set; }

    public DateTime CreatedAt { get; set; }
}
