using System.Text;
using CKYC.Core.Configuration;

namespace CKYC.Fvu;

/// <summary>
/// Generates the FVU_RUN_UTILITY.exe config.yaml for a single batch run. The backend
/// section is intentionally omitted — the Command-Line FVU bundles and auto-starts its
/// own Spring Boot backend JAR and embedded JDK.
/// </summary>
public static class FvuConfigGenerator
{
    public static string Build(
        string inputFolder,
        string docFolder,
        string outputFolder,
        string logFolder,
        FvuSettings fvu)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by CKYC Processor — FVU run configuration");
        sb.AppendLine($"input_folder: {ToYamlPath(inputFolder)}");
        sb.AppendLine($"doc_folder: {ToYamlPath(docFolder)}");
        sb.AppendLine($"output_folder: {ToYamlPath(outputFolder)}");
        sb.AppendLine();
        sb.AppendLine("api:");
        sb.AppendLine($"  base_url: {fvu.ApiBaseUrl}");
        sb.AppendLine($"  endpoint: {fvu.ApiEndpoint}");
        sb.AppendLine($"  trigger_source: {fvu.TriggerSource}");
        sb.AppendLine($"  request_timeout_seconds: {fvu.RequestTimeoutSeconds}");
        if (!string.IsNullOrEmpty(fvu.WorkspaceRoot))
            sb.AppendLine($"log_folder: {ToYamlPath(logFolder)}");
        return sb.ToString();
    }

    // YAML plain scalars: forward slashes avoid any escape ambiguity on Windows.
    private static string ToYamlPath(string path) => path.Replace('\\', '/');
}
