using System.Text;
using CKYC.Core.Configuration;

namespace CKYC.Sftp;

/// <summary>
/// Generates the <c>SFTPRunner.exe</c> <c>config.yaml</c>. The file is written to the
/// deterministic path held by <see cref="SftpPaths.ConfigPath"/> so the FVU upload folders
/// and the transport run always agree on where files come from and go.
/// <para>
/// Keys mirror the vendor integration document V1.2:
/// <c>sftp.host/username/password</c>, <c>proxy.*</c>,
/// <c>upload.ficode/individual-folder/legal-entity-folder</c>,
/// <c>download.path</c> and <c>report.outputFolder</c>.
/// </para>
/// </summary>
public static class SftpConfigGenerator
{
    public static string Build(SftpSettings sftp, SftpPaths paths)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by CKYC Processor — SFTP transport configuration.");
        sb.AppendLine("# Regenerated on every `sftp push` / `sftp pull`; edit appsettings.json instead.");
        sb.AppendLine("sftp:");
        sb.AppendLine($"  host: {Quote(sftp.Host)}");
        sb.AppendLine($"  username: {Quote(sftp.Username)}");
        sb.AppendLine($"  password: {Quote(sftp.Password)}");
        sb.AppendLine();
        sb.AppendLine("proxy:");
        sb.AppendLine($"  enabled: {(sftp.Proxy.Enabled ? "true" : "false")}");
        sb.AppendLine($"  host: {Quote(sftp.Proxy.Host)}");
        sb.AppendLine($"  port: {sftp.Proxy.Port}");
        sb.AppendLine($"  username: {Quote(sftp.Proxy.Username ?? string.Empty)}");
        sb.AppendLine($"  password: {Quote(sftp.Proxy.Password ?? string.Empty)}");
        sb.AppendLine();
        sb.AppendLine("upload:");
        sb.AppendLine($"  ficode: {Quote(sftp.FiCode)}");
        sb.AppendLine($"  individual-folder: {Quote(paths.IndividualFolder)}");
        sb.AppendLine($"  legal-entity-folder: {Quote(paths.LegalEntityFolder)}");
        sb.AppendLine();
        sb.AppendLine("download:");
        sb.AppendLine($"  path: {Quote(paths.DownloadFolder)}");
        sb.AppendLine();
        sb.AppendLine("report:");
        sb.AppendLine($"  outputFolder: {Quote(paths.ReportFolder)}");
        return sb.ToString();
    }

    /// <summary>Writes the generated config to <see cref="SftpPaths.ConfigPath"/> and returns that path.</summary>
    public static string Write(SftpSettings sftp, SftpPaths paths)
    {
        var directory = Path.GetDirectoryName(paths.ConfigPath);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);
        File.WriteAllText(paths.ConfigPath, Build(sftp, paths), new UTF8Encoding(false));
        return paths.ConfigPath;
    }

    // YAML double-quoted scalar: backslashes and quotes are the only characters that need escaping.
    private static string Quote(string value)
        => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
